"$schema" = 'https://starship.rs/config-schema.json'

palette = 'nordfox'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[palettes.nordfox]
red = "#bf616a"
green = "#a3be8c"
purple = "#b48ead"
yellow = "#ebcb8b"
os_bg = "#7e8188"
os_fg = "#232831"
dir_bg = "#a3be8c"
dir_fg = "#2e3440"
git_bg = "#ebcb8b"
git_fg = "#39404f"
lang_bg = "#81a1c1"
lang_fg = "#444c5e"

[os]
format = " [$name ]($style )"
style = "bold blue"
disabled = false

[username]
show_always = true
format = '\[[$user]($style)\]'

[directory]
format = '\[[ ğŸ“‚ $path]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
# conflicted = 'ğŸ³ '
# ahead = 'ğŸğŸ’¨ '
# behind = 'ğŸ˜° '
# diverged = 'ğŸ˜µ '
# up_to_date = 'âœ“ '
# untracked = 'ğŸ¤· '
# stashed = 'ğŸ“¦ '
# modified = 'ğŸ“ '
# staged = '[++\($count\)](green) '
# renamed = 'ğŸ‘… '
# deleted = 'ğŸ—‘ '

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
format = '\[[$symbol($version)]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cpp]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cmd_duration]
format = '\[[â±  $duration]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[golang]
format = '\[[$symbol($version)]($style)\]'

[haskell]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[solidity]
format = '\[[$symbol($version)]($style)\]'

[time]
disabled = false
time_format = "%R"
format = '\[[ ïº  $time ]($style)\]'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[â¯](bold #00ff00)"
error_symbol = "[âœ˜](bold #ff4444)"

[jobs]
number_threshold = 0
symbol_threshold = 0
symbol = 'jobs: '
